name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa uma vez por dia à meia-noite
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: SEU-USUARIO
          outputs: dist/github-contribution-grid-snake.svg

      - name: Enviar para o branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
